# Generated by Django 4.2.3 on 2023-07-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='user_id',
            new_name='user',
        ),
    ]
