# Generated by Django 4.2.3 on 2023-07-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notes',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
