# Generated by Django 4.2.3 on 2023-07-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notes_is_archive_notes_is_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(null=True, upload_to='./images'),
        ),
    ]
