# Generated by Django 4.2.3 on 2023-08-03 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0005_alter_notes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(null=True, upload_to='notes/images'),
        ),
    ]
