# Generated by Django 4.2.3 on 2023-08-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_notes_collaborators_alter_notes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='collaborators_label',
            field=models.ManyToManyField(related_name='collaborators_label', to='notes.notes'),
        ),
    ]
