# Generated by Django 4.2.3 on 2023-08-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_label_collaborators_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='collaborators_label',
            new_name='collaborators',
        ),
    ]
