# Generated by Django 4.2.3 on 2023-08-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_rename_collaborators_label_label_collaborators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='notes',
            name='label',
            field=models.ManyToManyField(related_name='label', to='notes.label'),
        ),
    ]
