# Generated by Django 4.2.3 on 2023-08-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_remove_notes_collaborators_collaborators'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collaborators',
        ),
    ]
