# Generated by Django 4.2.3 on 2023-08-12 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0011_delete_collaborators'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('READ_ONLY', 'read_only'), ('WRITABLE', 'writable')], default='READ_ONLY', max_length=200)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='notes.notes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='collaborators',
            field=models.ManyToManyField(related_name='shared_user', through='notes.Collaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
