# Generated by Django 4.2.3 on 2023-08-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_collaborators_notes_collaborators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborators',
            old_name='note_id',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='collaborators',
            old_name='user_id',
            new_name='user',
        ),
    ]
