# Generated by Django 4.2.3 on 2023-08-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'user_log',
            },
        ),
    ]
